metrics-server:

  revisionHistoryLimit: 0
  replicas: 3

  service:
    labels:
    #  Add these labels to have metrics-server show up in `kubectl cluster-info`
     kubernetes.io/cluster-service: "true"
     kubernetes.io/name: "Metrics-server"

  metrics:
    enabled: false

  tolerations:
  - operator: Exists
