apiVersion: inference.llmkube.dev/v1alpha1
kind: ModelRouter
metadata:
  name: model
spec:
  dataPlane: Proxy
  defaultRoute: gemma4
  defaultRouteStrategy: BackendNameMatch
  backends:
    - name: qwen3
      inferenceServiceRef:
        name: llamacpp-qwen3.5-9b
    - name: gemma4
      inferenceServiceRef:
        name: llamacpp-gemma4-26b-a4b
    - name: openwebui-embedding
      inferenceServiceRef:
        name: llamacpp-bge-m3
    - name: openwebui-tasks
      inferenceServiceRef:
          name: llamacpp-qwen3-0.6b
  proxy:
    replicas: 1
