apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-assets
  labels: 
    app.kubernetes.io/component: "assets"
    {{- include "common.labels" . | nindent 4 }}
  annotations: {{- .Values.tftp.annotations | toYaml | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - name: tftp
    port: 69
    protocol: UDP
    targetPort: tftp
  - name: assets
    port: 8080
    protocol: TCP
    targetPort: assets
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
