apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-http
  labels: {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: web
    targetPort: 3000
    port: 3000
    protocol: TCP
  - name: assets
    targetPort: 8080
    port: 8080
    protocol: TCP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
