apiVersion: v1
kind: Pod
metadata:
  name: bla
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ "echo", "'start'", "&&","sleep", "infinity" ]
      volumeMounts:
        - mountPath: /mnt/data
          name: restore-vol
  volumes:
    - name: restore-vol
      persistentVolumeClaim:
        claimName: nextcloud-db-3
  restartPolicy: Never
