apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: dawarich-immediate
spec:
  cluster:
    name: dawarich
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io