talos-cloud-controller-manager:
  fullnameOverride: talos-ccm

  daemonSet:
    enabled: true
  enabledControllers:
  - cloud-node
  - node-csr-approval

  resources:
    requests:
      cpu: 10m
      memory: 64Mi

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  transformations:
  - name: publicIPDiscovery
    nodeSelector:
    - matchExpressions:
      - key: platform
        operator: Exists
    features:
      publicIPDiscovery: true
  - name: zone
    nodeSelector:
    - matchExpressions:
      - key: hostname
        operator: Exists
    platformMetadata:
      Region: "njord-on-proxmox"
      Zone: |
        '{{ regexFindString "^.*-([a-z0-9]+)$" .Hostname 1 }}'
  - name: worker
    nodeSelector:
    - matchExpressions:
      - key: hostname
        operator: Regexp
        values:
        - ^talos-worker-.+$
    labels:
      node-role.kubernetes.io/worker: ""
