apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-topology-spread-to-cnpg-clusters
  annotations:
    policies.kyverno.io/title: Add Topology Spread Constraints to CNPG Clusters
    policies.kyverno.io/category: CloudnativePG
    policies.kyverno.io/subject: TopologySpreadConstraints
    policies.kyverno.io/description: Ensures CloudNativePG Cluster pods have topology spread constraints for each pod role for high availability.
spec:
  rules:
  - name: add-topology-spread-to-cnpg-cluster-podroles
    match:
      any:
      - resources:
          kinds:
          - postgresql.cnpg.io/v1/Cluster
          operations:
          - CREATE
          - UPDATE
    preconditions:
      all:
      - key: '{{`{{ has(request.object.spec.topologySpreadConstraints) }}`}}'
        operator: Equals
        value: false
    exclude:
      any:
      - resources:
          selector:
            matchExpressions:
            - key: metadata.deletionTimestamp
              operator: Exists
    mutate:
      patchStrategicMerge:
        spec:
          topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: 'kubernetes.io/hostname'
            whenUnsatisfiable: 'ScheduleAnyway'
            labelSelector:
              matchLabels:
                cnpg.io/cluster: '{{`{{ request.object.metadata.name }}`}}'
                cnpg.io/podRole: instance
          - maxSkew: 1
            topologyKey: 'topology.kubernetes.io/zone'
            whenUnsatisfiable: 'ScheduleAnyway'
            labelSelector:
              matchLabels:
                cnpg.io/cluster: '{{`{{ request.object.metadata.name }}`}}'
                cnpg.io/podRole: instance
