ollama:

  tolerations:
    - key: node-role.kubernetes.io/gpu
      operator: Exists
  extraEnv:
  # Keep the model loaded in GPU memory indefinitely (-1 = never unload)
  - name: OLLAMA_KEEP_ALIVE
    value: "-1"

  ollama:
    gpu:
      enabled: true
      draEnabled: true
      type: nvidia
      draDriverClass: gpu.nvidia.com
      draExistingClaimTemplate: ollama-nvidia
    # -- List of models to pull at container startup
    models:
      clean: true
      pull:
      - Qwen2.5-14B-Instruct-Q4_K_M
      - Qwen2.5-3B-Instruct

  persistentVolume:
    enabled: true
    storageClass: local-nvme
    size: 10Gi

  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      memory: 16Gi

  updateStrategy:
    type: Recreate
