---
apiVersion: v1alpha1
kind: KubeClusterConfig
clusterName: njord
endpoint: https://k8s.mobrockers.com:6443
---
apiVersion: v1alpha1
kind: DiscoveryServiceConfig
name: default
endpoint: https://discovery.talos.dev/
---
apiVersion: v1alpha1
kind: KubeNetworkConfig
podSubnets:
  - 10.244.0.0/16
# - fd66:10d7:2dbd::/112
serviceSubnets:
  - 10.96.0.0/12
# - fd58:c686:6b39::/112
---
cluster:
  etcd:
    extraArgs:
      listen-metrics-urls: https://0.0.0.0:2381
