---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
extraArgs:
  feature-gates: DRAExtendedResource=true,DRAPartitionableDevices=true,ResourceHealthStatus=true
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
extraArgs:
  feature-gates: DRAExtendedResource=true,DRAPartitionableDevices=true
---
apiVersion: v1alpha1
kind: KubeletConfig
extraArgs:
  feature-gates: DRAExtendedResource=true,ResourceHealthStatus=true
