apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-data
spec:
  instances: 2

  storage:
    storageClass: ceph-block-nrs
    size: 10Gi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: authentik-data-monitor
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": authentik-data
  podMetricsEndpoints:
  - port: metrics
