apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-data
spec:
  instances: 2

  storage:
    size: 3Gi

  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        "cnpg.io/cluster": authentik-data
        "cnpg.io/podRole": instance
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: authentik-data-monitor
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": authentik-data
  podMetricsEndpoints:
  - port: metrics
