apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: azure-blob-credentials
  namespace: authentik
spec:
  encryptedData:
    # echo -n "connectionstring" | kubeseal --cert https://sealed-secrets.mobrockers.com/v1/cert.pem --raw --name="azure-blob-credentials" -n authentik | clip.exe
    CONNECTION_STRING: ''