apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: authentik-backup-provider
spec:
  retentionPolicy: {{ .Values.database.backups.retention }}
  configuration:
    destinationPath: {{ .Values.database.backups.destination }}
    azureCredentials:
      connectionString:
        name: {{ .Values.database.backups.secretName }}
        key: {{ .Values.database.backups.azure.connectionStringKeyName }}
