apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
spec:
  instances: 2
  storage:
    size: 10Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName:  authentik-backup-provider
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: authentik-db-monitor
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": authentik-db
  podMetricsEndpoints:
  - port: metrics
