apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: overseerr
      app.kubernetes.io/name: overseerr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: overseerr
        app.kubernetes.io/name: overseerr 
    spec:
      automountServiceAccountToken: false
      containers:
        - name: overseerr
          image: '{{ .Values.overseerr.image.repository }}:{{ .Values.overseerr.image.tag }}'
          env:
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - containerPort: 5055
              name: http
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: overseerr-data
