apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: llamacpp-qwen3.5-9b
spec:
  image: ghcr.io/ggml-org/llama.cpp:server-cuda13-b10450
  modelRef: qwen3.5-9b
  runtime: llamacpp
  mode: chat
  contextSize: 16384
  jinja: true
  parallelSlots: 1
  cacheTypeK: q8_0
  cacheTypeV: q8_0
  flashAttention: true
  speculativeDecoding:
    type: disabled # mtp
  tolerations:
    - key: node-role.kubernetes.io/gpu
      operator: Exists
  extraArgs:
    - "--kv-unified"
