kubechecks:
  configMap:
    create: true
    env:
      KUBECHECKS_ARGOCD_API_INSECURE: 'true'
      KUBECHECKS_ARGOCD_API_PLAINTEXT: 'true'
      KUBECHECKS_ARGOCD_API_SERVER_ADDR: argocd-server.argocd

      KUBECHECKS_SCHEMAS_LOCATION: https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json

      KUBECHECKS_TIDY_OUTDATED_COMMENTS_MODE: delete
      KUBECHECKS_MAX_CONCURRENCT_CHECKS: '10'
      KUBECHECKS_LOG_LEVEL: warn

      KUBECHECKS_WEBHOOK_URL_BASE: https://kubechecks.mobrockers.com
      KUBECHECKS_VCS_TYPE: github

  deployment:
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 128Mi
        cpu: 150m

    replicaCount: 1

    image:
      name: ghcr.io/zapier/kubechecks
      tag: v2.1.0

    podSecurityContext:
#       runAsNonRoot: true
#       runAsUser: 32123
#       fsGroup: 32123

    securityContext:
#       allowPrivilegeEscalation: false
#       privileged: false
#       capabilities:
#         drop:
#           - ALL
#       readOnlyRootFilesystem: false

    envFrom:
      - secretRef:
          name: kubechecks-config

  ingress:
    create: true
    hosts:
      kubechecks.mobrockers.com:
        paths:
        - path: "/hooks"
          pathType: Prefix
    tls:
    - hosts:
      - kubechecks.mobrockers.com
