kubechecks:
  configMap:
    create: true
    env:
      KUBECHECKS_LOG_LEVEL: warn

      KUBECHECKS_ARGOCD_API_INSECURE: 'true'
      KUBECHECKS_ARGOCD_API_PLAINTEXT: 'true'
      KUBECHECKS_ARGOCD_API_SERVER_ADDR: argocd-server.argocd

      KUBECHECKS_WEBHOOK_URL_BASE: https://kubechecks.mobrockers.com
      KUBECHECKS_VCS_TYPE: github
      
      KUBECHECKS_TIDY_OUTDATED_COMMENTS_MODE: delete
      KUBECHECKS_REPLAN_COMMENT_MSG: '/kubechecks retry'
      KUBECHECKS_FALLBACK_K8S_VERSION: '1.30'
      KUBECHECKS_WORST_PREUPGRADE_STATE: Warning
      KUBECHECKS_REPO_SHALLOW_CLONE: 'true'
      KUBECHECKS_SCHEMAS_LOCATION: https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json

  deployment:
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 128Mi
        cpu: 150m

    replicaCount: 1
    revisionHistoryLimit: 0

    image:
      name: ghcr.io/zapier/kubechecks
      tag: v2.5.3

    podSecurityContext:
#       runAsNonRoot: true
#       runAsUser: 32123
#       fsGroup: 32123

    securityContext:
#       allowPrivilegeEscalation: false
#       privileged: false
#       capabilities:
#         drop:
#           - ALL
#       readOnlyRootFilesystem: false

    envFrom:
      - secretRef:
          name: kubechecks-config

  ingress:
    create: true
    hosts:
      kubechecks.mobrockers.com:
        paths:
        - path: "/hooks"
          pathType: Prefix
    tls:
    - hosts:
      - kubechecks.mobrockers.com

