{{- if .Values.privateGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: private
spec:
  gatewayClassName: envoy-gateway
  addresses:
    - value: {{ .Values.privateGateway.loadBalancerIP}}
      type: IPAddress
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: private-gateway-infra
  listeners:
   - name: web-https
     protocol: HTTPS
     port: 443
     hostname: '*.mobrockers.com'
     allowedRoutes:
       namespaces:
         from: All
     tls:
       mode: Terminate
       certificateRefs:
       - group: ''
         kind: Secret
         name: wildcard-mobrockers-com
   - name: apex-s3-mobrockers-com
     protocol: HTTPS
     port: 443
     hostname: 's3.mobrockers.com'
     allowedRoutes:
       namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: rook-ceph
     tls:
       mode: Terminate
       certificateRefs:
       - group: ''
         kind: Secret
         name: wildcard-s3-mobrockers-com
   - name: s3-mobrockers-com
     protocol: HTTPS
     port: 443
     hostname: '*.s3.mobrockers.com'
     allowedRoutes:
       namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: rook-ceph
     tls:
       mode: Terminate
       certificateRefs:
       - group: ''
         kind: Secret
         name: wildcard-s3-mobrockers-com
{{- end }}
