{{- if .Values.privateGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: private
  annotations:
    'cert-manager.io/revision-history-limit': "1"
    'cert-manager.io/cluster-issuer': cloudflare-letsencrypt-dns
spec:
  gatewayClassName: envoy-gateway
  addresses:
    - value: {{ .Values.privateGateway.loadBalancerIP}}
      type: IPAddress
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: private-gateway-infra
  listeners:
   - name: web-https
     protocol: HTTPS
     port: 443
     hostname: '*.mobrockers.com'
     allowedRoutes:
       namespaces:
         from: All
     tls:
       mode: Terminate
       certificateRefs:
       - group: ''
         kind: Secret
         name: star-mobrockers-com-tls
   - name: s3-https-root
     protocol: HTTPS
     port: 443
     hostname: 's3.mobrockers.com'
     allowedRoutes:
       namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: rook-ceph
     tls:
       mode: Terminate
       certificateRefs:
       - group: ''
         kind: Secret
         name: star-s3-mobrockers-com-tls
  #  - name: s3-https-wildcard
  #    protocol: HTTPS
  #    port: 443
  #    hostname: '*.s3.mobrockers.com'
  #    allowedRoutes:
  #      namespaces:
  #       from: Selector
  #       selector:
  #         matchLabels:
  #           kubernetes.io/metadata.name: rook-ceph
  #    tls:
  #      mode: Terminate
  #      certificateRefs:
  #      - group: ''
  #        kind: Secret
  #        name: star-s3-mobrockers-com-tls
{{- end }}
