apiVersion: v2
name: cert-manager
version: 1.0.0

dependencies:
  - name: cert-manager
    version: v1.19.4
    repository: https://charts.jetstack.io
  - name: trust-manager
    version: v0.21.1
    repository: https://charts.jetstack.io
