cert-manager:
  crds:
    enabled: true
    keep: false

  enableCertificateOwnerRef: true
  config:
    apiVersion: controller.config.cert-manager.io/v1alpha1
    kind: ControllerConfiguration
    leaderElectionConfig:
      namespace: cert-manager
    acmeDNS01Config:
      recursiveNameservers:
      - 1.1.1.1:53
      - 8.8.8.8:53
    acmeHTTP01Config:
      solverNameservers:
      - 1.1.1.1:53
      - 8.8.8.8:53
    enableGatewayAPI: true
    featureGates:
      ACMEHTTP01IngressPathTypeExact: false

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

trust-manager:
  crds:
    enabled: true
    keep: false

  defaultPackageImage:
    repository: quay.io/jetstack/trust-pkg-debian-bookworm
    tag: "20230311.0"
  app:
    metrics:
      service:
        enabled: true
        servicemonitor:
          enabled: true
