cert-manager:
  crds:
    enabled: true
    keep: false

  global:
    leaderElection:
      namespace: cert-manager

  enableCertificateOwnerRef: true
  config:
    leaderElectionConfig:
      namespace: cert-manager
    acmeDNS01Config:
      recursiveNameservers:
      - 1.1.1.1:53
      - 8.8.8.8:53
    acmeHTTP01Config:
      solverNameservers:
      - 1.1.1.1:53
      - 8.8.8.8:53
    enableGatewayAPI: true
    featureGates:
      ACMEHTTP01IngressPathTypeExact: false

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

trust-manager:
  crds:
    enabled: true
    keep: false

  defaultPackageImage:
    repository: quay.io/jetstack/trust-pkg-debian-bookworm
    tag: 20230311-deb12u1.0
  app:
    metrics:
      service:
        enabled: true
        servicemonitor:
          enabled: true
