ollama:

  nodeSelector:
    node-role.kubernetes.io/gpu: ""
  tolerations:
    - key: node-role.kubernetes.io/gpu
      operator: Exists

  persistentVolume:
    enabled: true
    storageClass: local-nvme
    size: 10Gi

  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      memory: 16Gi

  extraEnv:
  - name: OLLAMA_KEEP_ALIVE
    value: "-1"
