apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-cm
  labels:
    gatus-configfile: "1"   
data:
  seerr.yaml: |
    endpoints:
    - name: seerr
      url: https://seerr.mobrockers.com
      group: internal
      conditions:
      - '[STATUS] == 200'
    - name: seerr  
      url: https://seerr.mobrockers.com
      group: external
      conditions:
      - '[STATUS] == 200'
      client:
        dns-resolver: 'udp://1.1.1.1:53'
