apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 6 }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    {{- include "common.labels" . | nindent 8 }}
