apiVersion: v1
kind: Service
metadata:
  name: matter-hub
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 8482
      port: 8482
      protocol: TCP
  selector:
    app.kubernetes.io/instance: matter-hub
    app.kubernetes.io/name: matter-hub
