apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: public-gateway-podmonitor
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      path: /stats/prometheus
  selector:
    matchLabels:
        app.kubernetes.io/component: proxy
        app.kubernetes.io/managed-by: envoy-gateway
        app.kubernetes.io/name: envoy
        gateway.envoyproxy.io/owning-gateway-name: public
        gateway.envoyproxy.io/owning-gateway-namespace: {{ .Release.Namespace }}
