{{- if .Values.publicGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public
spec:
  gatewayClassName: envoy-gateway
  addresses:
    - value: {{ .Values.publicGateway.publicIP }}
      type: IPAddress
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: public-gateway-infra
  listeners:
   - name: web-https
     protocol: HTTPS
     port: 443
     hostname: '*.mobrockers.com'
     allowedRoutes:
       namespaces:
         from: All
     tls:
       mode: Terminate
       certificateRefs:
       - group: ''
         kind: Secret
         name: wildcard-mobrockers-com
{{- end }}
