{{- if .Values.publicGateway.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: public-gateway-infra
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              memory: 1Gi
      envoyService:
        annotations:
          'io.cilium/lb-ipam-ips': '{{ .Values.publicGateway.loadBalancerIP }}'
        externalTrafficPolicy: Local
        allocateLoadBalancerNodePorts: false
{{- end }}
