apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: llamacpp-qwen3-0.6b
spec:
  modelRef: qwen3-0.6b
  runtime: llamacpp
  image: {{ .Values.llamacpp.intel.image.repository }}:{{ .Values.llamacpp.intel.image.tag }}
  mode: chat
  contextSize: 4096
  jinja: false
  parallelSlots: 2
  tolerations:
    - key: node-role.kubernetes.io/gpu
      operator: Exists
  extraArgs:
    - --kv-unified
    - --reasoning
    - "off"