image:
  registry: ghcr.io
  repository: linuxserver/netbootxyz
  tag: 0.7.4

tolerations:

resources: {}

podSecurityContext:
  fsGroup: 5000

securityContext:
  runAsGroup: 5000
  capabilities: {}

persistence:
  config:
    size: 50Mi
    labels: {}
  assets:
    size: 5Gi
    labels: {}

route:
  enabled: false
  apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  annotations: {}
  hostnames:
    - netboot.example.com
  parentRefs: []
  filters: []
  matches: []

ingress:
  enabled: true
  domain: netboot.mobrockers.com
  class:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: |-
        http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |-
        https://netboot.mobrockers.com/outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
        Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
  tls:
    enabled: true
    secretName:

tftp:
  annotations: {}
