apiVersion: v1
kind: Service
metadata:
  name: wyoming-piper
spec:
  type: ClusterIP
  ports:
  - name: wyoming
    port: 10200
    targetPort: 10200
    protocol: TCP
  selector:
    app.kubernetes.io/instance: wyoming-piper
    app.kubernetes.io/name: wyoming-piper
