apiVersion: v2
name: dawarich
version: 0.0.0

dependencies:
- name: dawarich
  version: 7.0.0-copilot-fix-b1e7f59f-06cb-4428-ad2b-f23ad7dad330.b33a829
  repository: oci://ghcr.io/k8s-at-our-homes/helm-charts
