apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-data
  labels:
    velero.io/backup-class: noncritical
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
