apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route-oidc-secret
  namespace: prowlarr
spec:
  encryptedData:
    # echo -n "client-secret" | kubeseal --cert https://sealed-secrets.mobrockers.com/v1/cert.pem --raw --name="route-oidc-secret" -n prowlarr | clip.exe
    client-secret: AgAjhVurwsv7djT6KwuYoU4tmqJBlNN7Y2T+zwlW/OF7eRWxpjJsK2HpvAk+vyDL14y5PA9oQIoYKX8F8NPlYMJzfFbSFzPv7DyQwWxG6wz8AoozwLobt2sgdxSzDSz7dm6rXUFGJ+e4p4SMiUFdgSMk3diDinnbWcH1cQwNIuQUnqgYrpxIWL/gh4lewzmNjAm6GMfVLbrEpVbsrFnSc08hU930StaSFK5EBwSJIQarbq4AtsuhhHuSzR0O1XiH7QPTTVnhMhZE+mor1HtoM9txcQHGq2dzbodmubYRW0KgC8XOgImPuxrRK9lCQphDME4TLB+tGQ5872MCTWSLpc4mp6Qq5rTLUu/K9+Goc6K30q4wwiNdKplGRObgu7RyqAHCjiJqTgW/F8Plfgxy4anRQtuBPDTNeFc3jfyzyR5gVVrvS1dprhzl1hC6YGiWXLSqeb/r3h9T+l8Afofc1VJOtKGxU2r8PdPEYt8M08monPO3rDML2qBQ/ODVTC4KQM2r4QLW/Id7yGaa2twh5xLO0Rjv1qJtkYK1EKexXQVDUiCpM0nghwbpwRiN6CMvjMB35y423iIpf5RoJHdsQH1sCiIcXiT+sbbnJ7tTZ/LOWwBzC8FRCiFkbCvgAYYj5wpOnlCrultU+GgBCQM8U3dRThHd0suzAocoQD2i1KbLhq2ffpKQcjkRUhSWHf9dH3lttMWQOC0KpMN1Gobmip0wtqFL3gGq5eJgSNirrkEhK5a/Q+NGSxnsctBDtd7GKs0PXjh7WS6xcsDnbwNVvtakk+nkVRT93uLSOhrWgMKALOd9jwzZWdbpkWFaFO38nF6x8SZLGY4JWVP2EADw49Apz8Uzn3UAInLEV4uCrCXjZg==
