talos-cloud-controller-manager:

  logVerbosityLevel: 5
  daemonSet:
    enabled: true
  enabledControllers:
  - cloud-node
  - node-csr-approval

  resources:
    requests:
      cpu: 10m
      memory: 64Mi

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  transformations:
  - name: worker
    nodeSelector:
    - matchExpressions:
      - key: hostname
        operator: Regexp
        values:
        - .*-app\d+$
    labels:
      node-role.kubernetes.io/worker: ""
