apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route-oidc-secret
  namespace: radarr
spec:
  encryptedData:
    # echo -n "client-secret" | kubeseal --cert https://sealed-secrets.mobrockers.com/v1/cert.pem --raw --name="route-oidc-secret" -n radarr | clip.exe
    client-secret: AgBtMGmvXcf4A9D4Yu5A6c9EwXl5E8PdHkG+GgTyCrCrW4OP4q0vlxikhFNxyLDChwWhnrknywEuPy3J4/MgIOUwAR1Llc1URpsEtdDPrnUM4pvTMU+C6wlZIB3lRZz+FV97LibGP+aaQJNoR5hjjf1Zt9znTW3+7PGmvQ/vPza23Y177isZaarJwpWaysRuyHN/idQORzpHy1uXzGqtD1hYiVAcIxbxvHgrAS7Y7532zUmDd5AvBW++1Z9nTPq2a0M+Qls195aXeY6tiynTmovueZad4C+7+W8kEmEvJW7TglMl8jEqePAHZ+6kuoG3d6EMQklvF9BzLmu2Cy3Ce1VY+prIrSk2iWvM2ivgcHGu532zugH+LpgMW7vJgD6ZhrhEyY7wd8QS9SURtOpBW9utHNnPPcethrpQkBbAt+gNOg77Fv+cG/ssxPHd3Bmyuh2W8jugrh9bi7UXqwclUsFb9TjiSGscTNoM0gQJuBpQf12qtlusNRLB/H5VyFqK9TKHKzA15MemFWMW2Y5XiLBROcEOP06Z2V05sjeCA/E3xqLfQUblpFPOq/YN7kuIKPm83WVmDtaND+O2HVX3EnCM0fiH5/dumrpacH/+0rGO/Z/+gztTpBhNbhIPZu5tfoTcgCGLdzYMhxyp2dudQgMaSsTAXnr/rKDkPs9XIC413V1uR8mgsEVsKRR0J49fiDZigqEi3mIN9EnybaghE4RxxI2lNJMv2Q9Cc1IWPdv7wAR/1vIdZlxZtbRR6bb85myyTD4p/p3R5+HbUnz1vcZHI1kxvjx+pmmNfz+X1JYgVP9fvQ+5q90IbgA28kxMiCpttG94vJVQjnuBU2N1yux9CdbRwjAF6OT+Oom9Sm+MHA==
