apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: i915
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  spec:
    devices:
      requests:
      - allocationMode: ExactCount
        count: 1
        deviceClassName: gpu.intel.com
        name: i915
