apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  capacity:
    storage: 2Ti
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: 9fb4c9a5-90e2-42b3-a4b7-973ede3b4ed5
    volumeAttributes:
      server: truenas.mobrockers.com
      share: /mnt/slow/media
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
spec:
  storageClassName: ""
  volumeName: plex-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
