---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: AgDTlOsTEJ2ju6oWHfkGPudhQ+GEJSUbNqpnYPX88a3ll9t9stWNTiTETZ6NXHxKf8XX/DRnktH3yTqOhPz3SCTPRmVoxOGIjGwQ5gbd0aUoGVD0EKkHJfEp5CwJK8VZVCUtI2YTPCIgGojN5/ykVI1b/9uPvfT4agloVnKhfbREIoBimzXuG2tz1X4t0+QK4DR7mhZokG4KEQMfSh7rD/OoKCujON6XeADWkyUas7ZBq/QAV/dsNNHGxzp1u5cgGZIzl0eiVi1HS2OBHx+XI60g2811PybBBSXzBIBAj+7QJGPftskBa9gzNEP0dZNbK5Bg5UFh6ciIUFd1U6nG/771rl49qnlAYVivrWH9wSenvPzKvtbM0WacvaiyrPerhQdBgUsk7tGQrwUh20EQItPQsnmygPBLTyxeecsGzKdOufoe4oCCZ21aeMHKxMzw7o9TvEsAVFM56Yl/sS/zGGyiaFs/4Uihjzv2EKkTeljbZ1VekugjvTlhAxjbI73muqtPGMbO9ICMcsCt6HY/WC9vQh9M6+c4X2zP1BQ3HHvcCGv2IbAeYmQfpBLHWd81rKxtIwwhqkCfc2xKIguFt+0fAu28jo4O19q2aS7DwBpG5lpRX3ir/EAFuVS88SZ7m2fSHx3wjM09TcReb/jU++dZBi0zdlEGl2TRLVPaZzFXjETQcZRDbPgTTka1XB5/xWbuE+n5GA9BWiRoTjbmLCxs8f9fUz6ru4HLFkI8/Xcbfidbj8fuiz3ryd/b4D+Rp6fODV2q4Cr63mEvdW1mS68JGycL4soVHh4EOB9cHWnAYg7q98vn3qZyJVyc67bltALFz8Q=
    username: AgB/lruqFndMIrSSOPPq7XWRfxkkxyRcjlyHKk/P+v6rCmbAKvOHGKFHTneIBhur+nywb3L59UO2j+20cOm03XxifEcQBhIQgqP8CO6C8lT+j+wGoIhq+7eD3riX6QFocUvD+OsLA2iBYanWPawIRJMIoc3FyhFBeL7yB3rcPF8b5MRgQEuFwCQloBCJyd4vTdycv74MEhGbuwOkXYEov8LK/W9ruVlMBdRM4bEOg9h7UFSgeID0legqkDEQ0Ly9ViPOZYQ68ag66HJsKSAMlyG2/mLsFim5B67IC3Fg293aTiCHZdWo9he1O4v/v4dxZWnSxZHuApKU+acB1uM1FaJbhMfDROKR9mp2foORK1Ga61P7UvorMU6hGn7XQYm54ztWc7LUXA5oYJxEML7+QTM1+kFjOsAFK4zY1xDyegfYgPhn0/ABSO6vE4MjRTnrQM7XsWz+0lWm/mtDHhtXwECBsrret5+vJdQsMS/gLSG6WHUSn/bLqvJGIOqmo/Gp+C+9YlJhze3gizZW9SUBDHMMwjmo+4X0cgBxXVEsAXK0j+ahd2+R33qYI4hI7Wb1s91D3O6F7wlYMbT72jE5OaJOcHzKHzrw+toAqX01ro3ufFfct/8fnddPV3I5343eUlIYWx8p4V5Ik943NatJ4tRaydrPzdd2S8txx8lCRwntoF5qrfTQi7aQp+jM4ZH79RtGBHHbgA==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-credentials
      namespace: nextcloud
