---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: AgA47sLB7Izd9Our74+UxDkf1lXWIR6jkGpF/eX4BF3qvom6SDtzRvjgpVifb/V5FPk9YHMKtjkulOn0mIZfVzYx0hX355/fmKfFP6uHBIt3jM7rvisak1IN/GLHX/aG4OK+X9CY8btjEU53RJ1cMJGde6/+CmgR4hldbUHdm3oCKHnk+ko1hP0zJkfOrFJqlubWMYGzfzhNat09S8ukeNjBkI5l4FFX41SJN3C2QROLglrXhSCIFO698ee80B9zz4qSdmfyTyHWIbCx/vpH7XswqZcCTeXjgLudAZ6eaOQnLKxR+ulfdYHFLhhn+44QFlP7G6WzpPYrraU/RJvV2DKN6ExwF2+fiREoXWSppJICnDxdSRA7tKCRQWXrRBLc5AsKfg8U74+/F3XEhMeld5DJK7Rh2oxMOfVqgegTKP2e/PbxUoQMz6HaUV5DWBZh09tEo4OCq+jPZN9xr6orAPPgY6SvhxHA1nWwhgCIcOGCiYmRjpA8gBhKRa+pGNTwTkBOy6pHUFHdAocKRqtgjUVdkb4GgkD8N23gwyq5Aqe4m/z2/w0t5pQGetZ5hGbAbscaxZNYZLxBdmbmB36NA1uD+SEOhCsorF0PmS34cWKBBWF3854fLtTuYx+sz9JJLce2LII0LPB0yKCuwr/LgFkRzBJ/sLTv0Li1IXTTU0RZREJOILYxtFWqeB83Rmt6DZWYv2cjNkl4R3V5GLS/3+I/hfWOL9AMAjkIm1QyvqDf22ZmKsset2zZLOXVp+rFOiq7orsxaFI7S0kLQtcitIO/Hois4P98Ci5hMoL2rWSiUbINwZ5Tokbt6cGspsKxYnF5kQ==
    username: AgAm3Z935Qsy2u8KMHNZX3QdNzX8LMLEO2WtsWUuMZL8PMfodh8StvK4tSsFWh629xnEfl43LlictzqpdAoRC02gpQkyMVKaNkuWMVSfhdqPbNOKJw12XUSiANriVYG8mlMYsjn/s0GtlufOJuSlYHdmWss40j6NkwlsOjJq1Qw3/1/cgSG8oC55fAMjOrUApHn14Stt/Kj0moHcfGtuiwLvQBmL5r6H+Xi7i7Y8lrFSVwdO2tZOwwElGczEXO+PlPRbbYwDiDmFkvQxtsIjWL5XdDmbTnWuOl81ve3i0JpTOlsbm5nUG5HWA5uXhvQLLLNGhpkGNu+2eccnzFytAr78GvtbXNumojGYY5nuNEub8OOVMhBMDq+iNpo9WllyqEdcu80mUMMwlqbK0kBT3Vsq/ko3gNmw10c8yieNbweshQVyBkXbW53O8dOzLf9Wtt51gWdlYJ1VQ+eiATF/z9CC2lCX/uAO/EwLfWl+OkvvDBjGRWeOq2I1QjYkJ4lYgg0aRw3HQrITKve/J8pp9+hDbA0cdz1K6aiUtZbPveTlsTZ6K2WRee+KIZ/duMqKPHwCbTXIwsXEUw78dg7gtZA5VtWjv6BPqnIo7Xr3C66J7Qr6Rdm0rhGI5EYMgoQ/d2ri8E3k3mctPcAsDEhyzmc/5UlXIUvuoGzznHsiTXne/THYEhIMiukSYOV8jE9uBshBbTGCiQ==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-credentials
      namespace: nextcloud
