---
machine:
  nodeLabels:
    topology.kubernetes.io/zone: '2'
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: off
hostname: njord-2-cp1
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 10.0.102.10
link: enp1s0
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: enp1s0
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp1s0
addresses:
  - address: fdf9:dc00:d0eb:66::22/64
routes:
  - gateway: fdf9:dc00:d0eb:66::1
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp0s20f0u4
addresses:
  - address: 10.0.104.52/24
routes:
  - destination: 10.0.104.0/24
    gateway: 10.0.104.1
mtu: 9000
