apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: njord-3
spec:
  parallelism: 2
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.13.8
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: '3'
  policy:
    waitForVolumeDetach: true
  healthChecks:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
