apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: njord-3
spec:
  parallelism: 1
  talos:
    version: {{ .Values.talos.image.tag }}
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: 'njord-3'
  policy:
    waitForVolumeDetach: true
  healthChecks:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
