apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: njord-123
spec:
  parallelism: 1
  talos:
    version: {{ .Values.talos.image.tag }}
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: 'njord-123'
  policy:
    waitForVolumeDetach: true
