apiVersion: v1
kind: ConfigMap
metadata:
  name: scenes
  labels:
    home-assistant-config: "1"
  annotations:
    io.home-assistant/config-folder: "/config/scenes"
data:
{{ (.Files.Glob "configuration/scenes/**.yaml").AsConfig | indent 2 }}
