apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  labels:
    home-assistant-config: "1"
  annotations:
    io.home-assistant/config-folder: "/config/scripts"
data:
{{ (.Files.Glob "configuration/scripts/**.yaml").AsConfig | indent 2 }}
