apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: sabnzbd
      app.kubernetes.io/name: sabnzbd
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sabnzbd
        app.kubernetes.io/name: sabnzbd 
    spec:
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: sabnzbd
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PUID
          value: '1000'
        - name: PGID
          value: '5000'
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /config
        - name: media
          mountPath: /media
        livenessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 5
          periodSeconds: 10
      - name: exportarr
        image: '{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}'
        args:
        - sabnzbd
        env:
        - name: PORT
          value: "9707"
        - name: URL
          value: "http://localhost:8080"
        - name: ENABLE_ADDITIONAL_METRICS
          value: "true"
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: api-key-secret
              key: api-key
        ports:
        - name: metrics
          containerPort: 9707
        volumeMounts:
        - name: data
          mountPath: /config
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sabnzbd-data
      - name: media
        persistentVolumeClaim:
          claimName: media-library
