apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway-servicemonitor
spec:
  endpoints:
    - port: metrics
    - port: ratelimit
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-helm
      control-plane: envoy-gateway
