certificates:
  - name: wildcard-mobrockers-com
    dnsNames:
      - 'mobrockers.com'
      - '*.mobrockers.com'
  - name: wildcard-s3-mobrockers-com
    dnsNames:
      - 's3.mobrockers.com'
      - '*.s3.mobrockers.com'

privateGateway:
  enabled: true
  loadBalancerIP: 10.0.103.21

publicGateway:
  enabled: true
  loadBalancerIP: 10.0.103.22
  publicIP: 87.212.115.7
