cloudnative-pg:
  fullnameOverride: cloudnative-pg
  monitoring:
    podMonitorEnabled: true
    grafanaDashboard:
      create: true

plugin-barman-cloud:
  fullnameOverride: cloudnative-pg-plugin-barman-cloud
#   resources:
#     requests:
#       cpu: 100m
#       memory: 128Mi
#     limits:
#       memory: 512Mi
