spegel:
  revisionHistoryLimit: 0

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true

  spegel:
    logLevel: "WARN"
    containerdRegistryConfigPath: /etc/cri/conf.d/hosts

  serviceMonitor:
    enabled: true

  grafanaDashboard:
    enabled: true
