spegel:
  revisionHistoryLimit: 0

  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
  - key: node.cilium.io/agent-not-ready
    operator: Exists
  - key: node.kubernetes.io/unreachable
    operator: Exists

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true

  spegel:
    logLevel: "WARN"
    containerdRegistryConfigPath: /etc/cri/conf.d/hosts

  serviceMonitor:
    enabled: true

  grafanaDashboard:
    enabled: true
