{{- if .Values.initSecretJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-init-secret-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: init-secret-job
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-init-secret-job
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-init-secret-job
    namespace: {{ .Release.Namespace }}
{{- end }}
