{{- if .Values.initSecretJob.enabled }}
{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- $fullname := if .Values.fullnameOverride ((.Values.fullnameOverride | trunc 63) | trimSuffix "-") (if (contains $name .Release.Name) (.Release.Name | trunc 63 | trimSuffix "-") (printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-")) }}
{{- $chartName := printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}-init-secret-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: init-secret-job
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ $chartName }}
{{- end }}
