{{- if .Values.initSecretJob.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-init-secret-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: init-secret-job
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end }}
