apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
spec:
  storageClassName: ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.persistentVolume.size }}
