nextcloud:
  replicaCount: 1

  image:
    flavor: fpm

  phpClientHttpsFix:
    enabled: true
    protocol: https

  ingress:
    enabled: true
    tls:
    - hosts:
      - nextcloud.mobrockers.com

  nginx:
    enabled: true

  nextcloud:
    host: nextcloud.mobrockers.com

    objectStore:
      s3:
        enabled: true
        host: rook-ceph-rgw-ceph-objectstore.rook-ceph.svc
        port: 80
        ssl: false
        bucket: nextcloud-7c6ee2db-1c20-4088-9e57-ab57fef65a3b
        usePathStyle: true
        existingSecret: nextcloud-bucket
        secretKeys:
          accessKey: AWS_ACCESS_KEY_ID
          secretKey: AWS_SECRET_ACCESS_KEY

    # existingSecret:
    #   enabled: true
    #   secretName: nextcloud-credentials
    #   usernameKey: username
    #   passwordKey: password

    mail:
      enabled: false

    # resources:
    #   limits:
    #     memory: 256Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi

    extraInitContainers :
    - name: config-loader
      image: ghcr.io/kiwigrid/k8s-sidecar/1.30.3
      restartPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ "ALL" ]
      env:
      - name: IGNORE_ALREADY_PROCESSED
        value: "true"
      - name: LABEL
        value: "nextcloud-config"
      - name: FOLDER
        value: /config
      - name: RESOURCE
        value: "both"
      volumeMounts:
      - name: nextcloud-main
        mountPath: /config
        subPath: config

  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: postgresql

    existingSecret:
      enabled: true
      secretName: nextcloud-db-app
      hostKey: host
      databaseKey: dbname
      usernameKey: username
      passwordKey: password

  cronjob:
    enabled: true

  persistence:
    enabled: true
    storageClass: ceph-filesystem
    accessMode: ReadWriteMany
    size: 8Gi

  # resources:
  #   limits:
  #     memory: 512Mi
  #   requests:
  #     cpu: 90m
  #     memory: 128Mi

  metrics:
    enabled: true
    info:
      apps: true
    serviceMonitor:
      enabled: true
