nextcloud:
  replicaCount: 2

  image:
    flavor: fpm

  phpClientHttpsFix:
    enabled: true
    protocol: https

  ingress:
    enabled: true
    tls:
    - hosts:
      - nextcloud.mobrockers.com
    annotations:
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/server-snippet: |-
        server_tokens off;
        proxy_hide_header X-Powered-By;
        rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
        rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
        location = /.well-known/carddav {
          return 301 $scheme://$host/remote.php/dav;
        }
        location = /.well-known/caldav {
          return 301 $scheme://$host/remote.php/dav;
        }
        location = /robots.txt {
          allow all;
          log_not_found off;
          access_log off;
        }
        location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
          deny all;
        }
        location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
          deny all;
        }

  nginx:
    enabled: true

  nextcloud:
    host: nextcloud.mobrockers.com

    objectStore:
      s3:
        enabled: true
        host: rook-ceph-rgw-ceph-objectstore.rook-ceph.svc
        port: 80
        ssl: false
        bucket: nextcloud-7c6ee2db-1c20-4088-9e57-ab57fef65a3b
        usePathStyle: true
        existingSecret: nextcloud-bucket
        secretKeys:
          accessKey: AWS_ACCESS_KEY_ID
          secretKey: AWS_SECRET_ACCESS_KEY

    existingSecret:
      enabled: true
      secretName: nextcloud-credentials
      usernameKey: username
      passwordKey: password

    mail:
      enabled: false

    # resources:
    #   limits:
    #     memory: 256Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi

  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: postgresql
    existingSecret:
      enabled: true
      secretName: nextcloud-db-app
      hostKey: host
      databaseKey: dbname
      usernameKey: username
      passwordKey: password

  cronjob:
    enabled: true

  persistence:
    enabled: true
    storageClass: ceph-filesystem
    accessMode: ReadWriteMany
    size: 8Gi

  # resources:
  #   limits:
  #     memory: 512Mi
  #   requests:
  #     cpu: 90m
  #     memory: 128Mi

  metrics:
    enabled: true
    info:
      apps: true
    serviceMonitor:
      enabled: true
