apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
spec:
  instances: 2

  storage:
    size: 5Gi

  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        "cnpg.io/cluster": nextcloud-db
        "cnpg.io/podRole": instance
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        "cnpg.io/cluster": nextcloud-db
        "cnpg.io/podRole": instance
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nextcloud-db-monitor
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": nextcloud-db
  podMetricsEndpoints:
  - port: metrics
