apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
  annotations:
    cnpg.io/reconciliationLoop: "disabled"
spec:
  instances: 2

  storage:
    size: 5Gi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nextcloud-db-monitor
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": nextcloud-db
  podMetricsEndpoints:
  - port: metrics
