apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
spec:
  instances: 1
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: nextcloud-backup-provider
  storage:
    size: 5Gi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nextcloud-db-monitor
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": nextcloud-db
  podMetricsEndpoints:
  - port: metrics
