apiVersion: v2
name: intel-gpu-resource-driver
version: 0.0.0

dependencies:
  - name: intel-gpu-resource-driver-chart
    version: 0.9.0
    repository: oci://ghcr.io/intel/intel-resource-drivers-for-kubernetes
