intel-gpu-resource-driver-chart:

  tolerations: []

  cdi:
    staticPath: /run/cdi

  nodeFeatureRules:
    enabled: true

xpumd:
  image:
    repository: ghcr.io/intel/xpumanager/xpumd
    tag: 2.0.0
  gpuAccess: dra
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"
  prometheus:
    monitor: true
    release: ~
  grafana:
    dashboards: true
    namespace: ~
  tolerations: []
