intel-gpu-resource-driver-chart:
  cdi:
    staticPath: /run/cdi

  nodeFeatureRules:
    enabled: true
  kubeletPlugin:
    tolerations:
      - key: node-role.kubernetes.io/gpu
        operator: Exists
    healthMonitoring:
      enabled: false
