intel-gpu-resource-driver-chart:

  tolerations: []

  cdi:
    staticPath: /run/cdi

  nodeFeatureRules:
    enabled: true

  xpumdEnabled: true

  xpumd:
    gpuAccess: dra
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    prometheus:
      monitor: true
      release: prometheus
    grafana:
      dashboards: true
      namespace: prometheus
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/gpu
        operator: Exists
        effect: NoSchedule

  kubeletPlugin:
    # Health monitoring configuration
    healthMonitoring:
      # Provide -m flag to kubelet-plugin to actively monitor GPU health via xpumd.
      enabled: true
