apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-revisionhistorylimit-zero
  annotations:
    policies.kyverno.io/title: Set revisionHistoryLimit to Zero
    policies.kyverno.io/category: GitOps
    policies.kyverno.io/subject: Workloads
    policies.kyverno.io/description: Ensure all Deployments, StatefulSets, and DaemonSets have revisionHistoryLimit set to 0 to avoid retaining old ReplicaSets and Pods.
spec:
  rules:
    - name: set-revisionhistorylimit-zero
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
              operations:
                - CREATE
                - UPDATE

      context:
        - name: excludedOwnerKinds
          variable:
            value:
              - Prometheus
              - Alertmanager
              - ThanosRuler
          
      preconditions:
        all:
          - key: '{{ request.object.metadata.deletionTimestamp || "" }}'
            operator: Equals
            value: ''
          - key: >-
              {{ (request.object.metadata.ownerReferences[?contains(excludedOwnerKinds, kind)]) | length(@) }}
            operator: Equals
            value: 0

      mutate:
        patchStrategicMerge:
          spec:
            revisionHistoryLimit: 0
