apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: sonarr
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sonarr
        app.kubernetes.io/name: sonarr 
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 5000
        fsGroup: 5000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: sonarr
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 8989
          name: http
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /config
        - name: media
          mountPath: /media
        livenessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 5
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sonarr-data
      - name: media
        persistentVolumeClaim:
          claimName: media-library
