apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr
spec:
  ports:
    - name: http
      port: 8989
      targetPort: http
    - name: metrics
      port: 9707
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
