apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph.cephfs.csi.ceph.com
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-67c659f3-838f-47d5-9c15-7d80c8710cfc-bazarr
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Ti
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    volumeAttributes:
      staticVolume: "true"
      clusterID: rook-ceph
      fsName: ceph-filesystem
      pool: ceph-filesystem-data0
      storage.kubernetes.io/csiProvisionerIdentity: 1744229175725-2701-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-734b5df5-5692-45b5-bdb3-07963cdf7d88
      rootPath: /volumes/csi/csi-vol-734b5df5-5692-45b5-bdb3-07963cdf7d88/cf58ab99-94c4-47fe-bdca-58959952b69d
      subvolumePath: /volumes/csi/csi-vol-734b5df5-5692-45b5-bdb3-07963cdf7d88/cf58ab99-94c4-47fe-bdca-58959952b69d
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-734b5df5-5692-45b5-bdb3-07963cdf7d88-bazarr
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    nodeStageSecretRef:
      name: rook-csi-cephfs-node-user
      namespace: rook-ceph
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
spec:
  storageClassName: ceph-filesystem
  volumeName: pvc-67c659f3-838f-47d5-9c15-7d80c8710cfc-bazarr
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
