image:
  repository: ghcr.io/linuxserver/bazarr
  tag: 1.6.0

metrics:
  image:
    repository: ghcr.io/onedr0p/exportarr
    tag: v2.3.0

route:
  enabled: true
  hostnames:
  - bazarr.mobrockers.com
  parentRefs:
  - name: private
    namespace: envoy-gateway
    sectionName: web-https
  - name: public
    namespace: envoy-gateway
    sectionName: web-https
  additionalRules:
    - timeouts:
        request: "300s"