apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: azure-credentials
  namespace: velero
spec:
  encryptedData:
    credentials: |
      AgAoXci3LgS7BA4uPlR7M6yFVlmtXx3ei+1CKFme3MYnBtp+Slz1TzcSotxVZTzGhIwmAw737NFnPzWJDPCiPuuc54LmJBvqH8IhGRG7muMLixc4CQcsohQIRWIj8nUe+4fPN+7oh5XgXkR6KBRNinNtjsBsWe0CF5C3ca+81dKZdEYnZlhLhobyPqiFAsNEp8AhJkh8LzuVV75QYlr6s9Ydoj+Ioj2NfjZsu2vU6ECpmSRRODI0NVUHO0tmprJ7mijM0u6d55YhXfpB9M14LsXcl55KBHMtS26jYjD7dFqf3HjK5kxsEetH3oX81pZtAqzNLlPVRfeZ58tIEAS+ogoRb5imAe62sZpEDYH04nRdph0Nfmr+D+zMN9dSd7Yl4jyRh/wQf4/tw4tPOZ4b/4kI6nY/oXJSE2FWW/IWcTg8L7a0KxBDyxQw8usBXHnrM/WfAMcLUFAzuc66IjJNYCErR9sj0lcQzjQLpucVOg27uQR4qGn821pynyBnvlJRAVeMvzqyvsBTTtg2Ets/gnmv0oEirL4hc5kCQVyrSJLOoHUqdDpX5ZoYhTHnSaA/U6uF3T5QMsNcBOdGvC+1cAqdssJYZSKweu4m09IBhR9dfB30F6cqeX0prSfHVuVWYBqopKJPgNRnnKNi9a1s7lzkbdLUhUe8SkARMSb3yWie8LIYXMXV5pEXPKCYNgV+wYB6wfIl2XhT0f4wWTf1Cw6YhL3szk4OTAUWwNAzwLfCAmlBuNKEusvXJcrPJrYgDnfsIleW2MHZwbDD/UwBhshPnOxuOajLn9q4yJSsstleslOw7KuRBYgmmxHkUWGS7QsUHCImpLsNCjCk/nYlaFYinubP2F5eNGbHxvrH4Vgk+I6M8U5E22PmsypMWOh9BwP9+aJopqeQSts+lPvEZ0o6L5fkdz2r

# cat credential.yaml | kubeseal --cert https://sealed-secrets.mobrockers.com/v1/cert.pem --raw --name="azure-credentials" -n velero | clip.exe

# AZURE_TENANT_ID=${AZURE_TENANT_ID}
# AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
# AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
