apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: cpu-embedding
spec:
  nodeSelector:
    kubernetes.io/hostname: njord-gpu1
  tolerations:
    - key: node-role.kubernetes.io/gpu
      operator: Exists
  modelRef: bge-m3
  runtime: llamacpp
  mode: embedding
  parallelSlots: 1
  contextSize: 4096
  batchSize: 4096
  uBatchSize: 4096
  extraArgs:
    - "--alias"
    - "bge-m3"
