apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-whisper
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: wyoming-whisper
      app.kubernetes.io/name: wyoming-whisper
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: wyoming-whisper
        app.kubernetes.io/name: wyoming-whisper
    spec:
      containers:
      - name: wyoming-whisper
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        ports:
        - name: wyoming
          containerPort: 10300
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PUID
          value: '1000'
        - name: PGID
          value: '5000'
        - name: WHISPER_MODEL
          value: '{{ .Values.model }}'
        - name: WHISPER_LANG
          value: '{{ .Values.language }}'
        - name: WHISPER_BEAM
          value: '{{ .Values.beamSize }}'
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            memory: 4Gi
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: wyoming-whisper-config
