apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-whisper-config
spec:
  storageClassName: ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
