tuppr:
  monitoring:
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
    dashboards:
      enabled: true

talos:
    image:
      repository: ghcr.io/siderolabs/talos
      tag: v1.14.0
kubernetes:
  image:
    repository: ghcr.io/siderolabs/kubelet
    tag: v1.36.4
