tuppr:
  monitoring:
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
    dashboards:
      enabled: true

talos:
    image:
      repository: ghcr.io/siderolabs/installer
      tag: v1.13.9
kubernetes:
  image:
    repository: ghcr.io/siderolabs/kubelet
    tag: v1.37.0
