external-dns:
  global:
    security:
      allowInsecureImages: true
  crd:
    create: true
  revisionHistoryLimit: 0
  image:
    registry: registry.k8s.io
    repository: external-dns/external-dns
    tag: v0.19.0

  policy: sync
  sources:
    - ingress
    - service
    - crd
    - gateway-httproute
    - gateway-tlsroute
    - gateway-udproute
    - gateway-tcproute
    - gateway-grpcroute

  provider: cloudflare
  cloudflare:
    secretName: "cloudflare-api-token"
    proxied: false
  zoneIdFilters:
  - 7ad202c85cb68e3a1df112d76d683078
  extraArgs:
    exclude-target-net: 10.0.0.0/8

  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 30Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
