external-dns:
  crd:
    create: true

  policy: sync
  sources:
    - ingress
    - service
    - crd

  provider: cloudflare
  cloudflare:
    secretName: "cloudflare-api-token"
    proxied: false
  zoneIdFilters:
  - 7ad202c85cb68e3a1df112d76d683078
  extraArgs:
    exclude-target-net: 10.0.0.0/8
    txt-new-format-only:

  resources:
    limits:
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 30Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
