apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: ollama-nvidia
spec:
  schema:
    name: OpenAI
  backendRef:
    name: ollama-nvidia
    kind: Backend
    group: gateway.envoyproxy.io
