apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud-config-loader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcloud-config-loader-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nextcloud-config-loader-role-binding
roleRef:
  kind: Role
  name: nextcloud-config-loader-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: nextcloud-config-loader
  namespace: {{ .Release.Namespace }}
