apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-loader
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: config-loader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: config-loader
    spec:
      serviceAccountName: nextcloud-config-loader
      containers:
      - name: config-loader
        image: ghcr.io/kiwigrid/k8s-sidecar:1.30.3
        env:
        - name: IGNORE_ALREADY_PROCESSED
          value: "true"
        - name: LABEL
          value: "nextcloud-config"
        - name: FOLDER
          value: /config
        - name: RESOURCE
          value: "both"
        volumeMounts:
        - mountPath: /config
          name: nextcloud-main
          subPath: config
      securityContext:
        fsGroup: 82
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumes:
        - name: nextcloud-main
          persistentVolumeClaim:
            claimName: nextcloud-nextcloud
