apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  labels:
    velero.io/backup-class: critical
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
