apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route-oidc-secret
  namespace: maintainerr
spec:
  encryptedData:
    # echo -n "client-secret" | kubeseal --cert https://sealed-secrets.mobrockers.com/v1/cert.pem --raw --name="route-oidc-secret" -n maintainerr | clip.exe
    client-secret: AgAI5TJ+DurM0X6XcaAwjPijkzkrHJXn1YzV5cIxqXnMUQh7NUWOcR3wkuxMbwESIfaiE4x/4QDSOq5UYphEQc6lFGdEfuwJaAyYpWaQZUGAFE14QulBcdshdzQn+xyDm6ufR199wB2Z2Z2hJ6PIcS0uzhK4lHVxMN6x+mqwM7ALVAI2Cr9pMohIhQ57lp5jpu/iJiduszcGCOF+Gj4y/ZfQh15FUvF36NOk2m7ymz8Tw4JGb520bcw4D3wo158WDlogmPHIgFkt6T/WHf8U1CzidOkYfrTNC1lOTjBQFr5GnbcRiryN7MT/oNnDQbrJrQNDTV7kRRA1aZgMb/sRNYg03gpCa2cYwLzVgZjBYFM4RkjixoK+Q6zvtHuRIhAreBQZeii1pQzdr06G69lLDxnsWJA7X8Xp4kAkiIRS2TcatsLmIwTRKl0qSvuidZW2cLYytBaJNkMcVxd3I6Ve3xbwNTwnQP49lGDsOjZ+/27RiNfBqdyAQzTPhMFlo/OPIvnt+9/2N7j9sN2baNkb0Mv0/LfccvM9YAjSsADI/RkgWGtGCvKXHYTscjxXyxVT/Ynd9rOwfb9gnmcA1Xd/Q1Fu00e6JdHq1p94ogmT0GSTX1wrjiPN8wYR7tu/2v4IQiPQHlOQjOXakIMwz1vNJwPstozdUpFBERjhMUCTVqnAql19orL2JdhbYnKPFDypSjDm43esbekBiy2qWVGb/sHbpodiy3abdhX4mgnNiPSQo/t3aoh11QzgAO4QMCLDxLTU+aePiWc7/BZm7x0hILfb8uY839+6grWqqXDqCTNeGCpqxUrPDQYy0ksnwtTH6tv3sfCmW8oIS4ikn0qIjjqVRjBdnkfFGHJkDUU/DNZWBg==
