{{- $route := range .Values.routes }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $route.name }}-proxy-service
spec:
  type: ExternalName
  externalName: '{{ $route.name }}.internal'
---
{{- end }}
