id: "trvzb_temperature_sensor_fallback_repair_creation"
alias: "TRVZB Temperature Sensor Fallback Repair Creation"
mode: queued
max: 20

trigger:
  # Explicit TRV selects
  - platform: state
    entity_id:
      - select.bedroom_radiator_temperature_sensor_select
      - select.hall_radiator_temperature_sensor_select
      - select.kitchen_radiator_temperature_sensor_select
      - select.living_room_radiator_temperature_sensor_select
      # - select.office_radiator_left_temperature_sensor_select
      - select.office_radiator_right_temperature_sensor_select
      # - select.shower_radiator_temperature_sensor_select
    id: state_changed

  # Bootstrap for “already in external_2/external_3”
  - platform: homeassistant
    event: start
    id: bootstrap

action:
  - variables:
      issue_prefix: "missing_external_temp"

      # Explicit mapping: TRV select -> VT last temp datetime sensor
      vt_map: >
        {{
          {
            'select.bedroom_radiator_temperature_sensor_select': 'sensor.bedroom_thermostat_last_temperature_date',
            'select.hall_radiator_temperature_sensor_select': 'sensor.hall_thermostat_last_temperature_date',
            'select.kitchen_radiator_temperature_sensor_select': 'sensor.kitchen_thermostat_last_temperature_date',
            'select.living_room_radiator_temperature_sensor_select': 'sensor.living_room_thermostat_last_temperature_date',
            'select.office_radiator_left_temperature_sensor_select': 'sensor.office_thermostat_last_temperature_date',
            'select.office_radiator_right_temperature_sensor_select': 'sensor.office_thermostat_last_temperature_date',
            'select.shower_radiator_temperature_sensor_select': 'sensor.shower_thermostat_last_temperature_date'
          }
        }}

  - choose:
      # ============================================================
      # Bootstrap pass
      # ============================================================
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'bootstrap' }}"
        sequence:
          - repeat:
              for_each: "{{ vt_map.keys() | list }}"
              sequence:
                - variables:
                    entity_id: "{{ repeat.item }}"
                    current_state: "{{ states(entity_id) }}"
                    friendly_name: "{{ state_attr(entity_id, 'friendly_name') | default(entity_id) }}"
                    mode_last_changed: "{{ states[entity_id].last_changed if states[entity_id] is not none else none }}"

                    vt_last_seen_sensor: "{{ vt_map.get(entity_id, '') }}"
                    vt_last_seen_raw: "{{ states(vt_last_seen_sensor) if vt_last_seen_sensor else 'unknown' }}"
                    vt_last_seen_dt: "{{ as_datetime(vt_last_seen_raw, none) }}"
                    vt_last_seen_age_min: >
                      {% if vt_last_seen_dt is not none %}
                        {{ ((as_datetime(now(), none) - vt_last_seen_dt).total_seconds() / 60) | round(0) }}
                      {% else %}
                        {{ none }}
                      {% endif %}

                    encoded_entity: "{{ entity_id | replace('.', '__d__') }}"
                    issue_id: "{{ issue_prefix }}__{{ encoded_entity }}"

                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ current_state in ['external_2', 'internal', 'internal_2'] }}"
                      sequence:
                        - service: repairs.create
                          data:
                            issue_id: "{{ issue_id }}"
                            title: "{{ friendly_name }} External Temperature Missing"
                            severity: error
                            domain: climate
                            persistent: true
                            description: >
                              **ERROR:** {{ friendly_name }} is currently in **{{ current_state }}**.

                              **VT last temperature date:**
                              {% if vt_last_seen_sensor %}
                              - Sensor: `{{ vt_last_seen_sensor }}`
                              - Value: {{ vt_last_seen_raw }}
                              {% if vt_last_seen_age_min is not none %}
                              - Age: {{ vt_last_seen_age_min }} minute(s)
                              {% endif %}
                              {% else %}
                              - No VT mapping configured for this TRV.
                              {% endif %}

                              **TRV mode info:**
                              - Current: `{{ current_state }}`
                              - Mode last changed: {{ mode_last_changed }}

                              Dismiss this repair when you’re satisfied; dismissal sets `{{ entity_id }}` back to **external**.

                    - conditions:
                        - condition: template
                          value_template: "{{ current_state == 'external_3' }}"
                      sequence:
                        - service: repairs.create
                          data:
                            issue_id: "{{ issue_id }}"
                            title: "{{ friendly_name }} External Temperature Intermittent"
                            severity: warning
                            domain: climate
                            persistent: true
                            description: >
                              **WARNING:** {{ friendly_name }} is currently in **external_3**.

                              **VT last temperature date:**
                              {% if vt_last_seen_sensor %}
                              - Sensor: `{{ vt_last_seen_sensor }}`
                              - Value: {{ vt_last_seen_raw }}
                              {% if vt_last_seen_age_min is not none %}
                              - Age: {{ vt_last_seen_age_min }} minute(s)
                              {% endif %}
                              {% else %}
                              - No VT mapping configured for this TRV.
                              {% endif %}

                              **TRV mode info:**
                              - Current: `external_3`
                              - Mode last changed: {{ mode_last_changed }}

                              Dismiss this repair after investigating; dismissal sets `{{ entity_id }}` back to **external**.

      # ============================================================
      # State-change pass (single entity)
      # ============================================================
    default:
      # Only act on real state transitions
      - condition: template
        value_template: >
          {{ trigger.from_state is not none
             and trigger.to_state is not none
             and trigger.from_state.state != trigger.to_state.state }}

      - variables:
          entity_id: "{{ trigger.entity_id }}"
          to_state: "{{ trigger.to_state.state }}"
          from_state: "{{ trigger.from_state.state }}"
          friendly_name: "{{ trigger.to_state.attributes.friendly_name | default(entity_id) }}"
          mode_last_changed: "{{ trigger.to_state.last_changed }}"

          vt_last_seen_sensor: "{{ vt_map.get(entity_id, '') }}"
          vt_last_seen_raw: "{{ states(vt_last_seen_sensor) if vt_last_seen_sensor else 'unknown' }}"
          vt_last_seen_dt: "{{ as_datetime(vt_last_seen_raw, none) }}"
          vt_last_seen_age_min: >
            {% if vt_last_seen_dt is not none %}
              {{ ((as_datetime(now(), none) - vt_last_seen_dt).total_seconds() / 60) | round(0) }}
            {% else %}
              {{ none }}
            {% endif %}

          encoded_entity: "{{ entity_id | replace('.', '__d__') }}"
          issue_id: "{{ issue_prefix }}__{{ encoded_entity }}"

      - choose:
          - conditions:
              - condition: template
                value_template: "{{ to_state in ['external_2', 'internal', 'internal_2'] }}"
            sequence:
              - service: repairs.create
                data:
                  issue_id: "{{ issue_id }}"
                  title: "{{ friendly_name }} External Temperature Missing"
                  severity: error
                  domain: climate
                  persistent: true
                  description: >
                    **ERROR:** {{ friendly_name }} transitioned **{{ from_state }} → {{ to_state }}**.

                    **VT last temperature date:**
                    {% if vt_last_seen_sensor %}
                    - Sensor: `{{ vt_last_seen_sensor }}`
                    - Value: {{ vt_last_seen_raw }}
                    {% if vt_last_seen_age_min is not none %}
                    - Age: {{ vt_last_seen_age_min }} minute(s)
                    {% endif %}
                    {% else %}
                    - No VT mapping configured for this TRV.
                    {% endif %}

                    - Mode last changed: {{ mode_last_changed }}

                    Dismiss this repair when you’re satisfied; dismissal sets `{{ entity_id }}` back to **external**.

          - conditions:
              - condition: template
                value_template: "{{ to_state == 'external_3' }}"
            sequence:
              - service: repairs.create
                data:
                  issue_id: "{{ issue_id }}"
                  title: "{{ friendly_name }} External Temperature Intermittent"
                  severity: warning
                  domain: climate
                  persistent: true
                  description: >
                    **WARNING:** {{ friendly_name }} transitioned **{{ from_state }} → external_3**.

                    **VT last temperature date:**
                    {% if vt_last_seen_sensor %}
                    - Sensor: `{{ vt_last_seen_sensor }}`
                    - Value: {{ vt_last_seen_raw }}
                    {% if vt_last_seen_age_min is not none %}
                    - Age: {{ vt_last_seen_age_min }} minute(s)
                    {% endif %}
                    {% else %}
                    - No VT mapping configured for this TRV.
                    {% endif %}

                    - Mode last changed: {{ mode_last_changed }}

                    Dismiss this repair after investigating; dismissal sets `{{ entity_id }}` back to **external**.
