id: 'trvzb_temperature_sensor_fallback_notification'
alias: TRVZB Temperature Sensor Fallback Alert
description: >
  Notify administrators when a TRVZB is in fallback mode (external_2 or
  external_3). Checks every 3 hours since TRVZB switches to fallback after
  2 hours of no external sensor updates. Auto-discovers all TRVZBs.
mode: single
trigger:
  # Time-based trigger - checks every 3 hours for minimal performance impact
  # TRVZB switches to fallback mode after 2 hours, so 3-hour checks are
  # sufficient
  - platform: time_pattern
    hours: '/3'
condition: []
action:
  # Check all temperature_sensor_select entities for fallback modes
  - repeat:
      for_each: >
        {% set ns = namespace(entities=[]) %}
        {% for entity in states.select
           | selectattr('entity_id', 'match', '.*_temperature_sensor_select$')
           | selectattr('state', 'in', ['external_2', 'external_3']) %}
          {% set ns.entities = ns.entities + [entity.entity_id] %}
        {% endfor %}
        {{ ns.entities }}
      sequence:
        - service: persistent_notification.create
          data:
            title: 'TRVZB Temperature Sensor Fallback Detected'
            message: >
              The TRVZB {{ state_attr(repeat.item, 'friendly_name') |
              default(repeat.item) }} is in {{ states(repeat.item) }} mode.

              This indicates the external temperature sensor has not sent
              updates for several hours and the TRV has fallen back to using
              its internal sensor.

              Please check:

              - Battery level of the external temperature sensor

              - Connectivity of the external temperature sensor

              - Pairing status between the TRV and external sensor

              Entity: {{ repeat.item }}

              Current state: {{ states(repeat.item) }}

              Time: {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
            notification_id: >
              trvzb_fallback_{{ repeat.item | replace('.', '_') }}
