id: "trvzb_temperature_sensor_reset_on_repair_remove"
alias: "TRVZB Reset Temperature Sensor Mode on Repair Dismissal"
mode: queued
max: 10

trigger:
  - platform: state
    entity_id: event.repair

condition:
  - condition: template
    value_template: >
      {% set a = trigger.to_state.attributes if trigger.to_state else {} %}
      {% set ev = a.get('event_type','') %}
      {% set iid = a.get('issue_id','') %}
      {{ ev == 'remove'
         and (iid.startswith('missing_external_temp__')
              or iid.startswith('user_missing_external_temp__')) }}

action:
  - variables:
      issue_prefix: "missing_external_temp"
      raw_issue_id: "{{ trigger.to_state.attributes.issue_id }}"
      normalized_issue_id: "{{ raw_issue_id | regex_replace('^user_', '') }}"
      encoded_entity: "{{ normalized_issue_id | replace(issue_prefix ~ '__', '') }}"
      target_entity_id: "{{ encoded_entity | replace('__d__', '.') }}"

  - service: select.select_option
    target:
      entity_id: "{{ target_entity_id }}"
    data:
      option: external
