id: "trvzb_temperature_sensor_fallback_repair_creation"
alias: "TRVZB Temperature Sensor Fallback Repair Creation"
description: >
  Create/overwrite a single repair per TRV based on temperature sensor mode changes.
  Uses VT "last temperature date" sensors as evidence (age/staleness).
  Repair is not auto-removed; dismissing the repair triggers reset-to-external via a
  separate automation.
mode: single

trigger:
  - platform: event
    event_type: state_changed

condition:
  - condition: template
    value_template: >
      {% set e = trigger.event.data.get('entity_id','') %}
      {% set to_s = trigger.event.data.get('new_state') %}
      {% set from_s = trigger.event.data.get('old_state') %}
      {{ e is match('^select\\..*_temperature_sensor_select$')
         and to_s is not none and from_s is not none
         and to_s.state != from_s.state }}

action:
  - variables:
      issue_prefix: "missing_external_temp"

      entity_id: "{{ trigger.event.data.entity_id }}"
      to_state: "{{ trigger.event.data.new_state.state }}"
      from_state: "{{ trigger.event.data.old_state.state }}"
      friendly_name: >-
        {{ trigger.event.data.new_state.attributes.friendly_name
           | default(entity_id) }}

      # simple reversible encoding for issue_id
      encoded_entity: >-
        {{ entity_id | replace('.', '__d__') }}
      issue_id: "{{ issue_prefix }}__{{ encoded_entity }}"

      # Derive room key from TRV select name:
      # select.<room>_radiator..._temperature_sensor_select -> <room>
      room_key: >-
        {{ entity_id
            | regex_replace('^select\\.', '')
            | regex_replace('_radiator.*$', '') }}

      # VT last-temperature-date sensor inferred from room key
      vt_last_seen_sensor: "sensor.{{ room_key }}_thermostat_last_temperature_date"
      vt_last_seen_raw: "{{ states(vt_last_seen_sensor) }}"

      vt_last_seen_dt: >-
        {% set v = vt_last_seen_raw %}
        {% if v not in ['unknown','unavailable','none',''] %}
          {{ as_datetime(v) }}
        {% else %}
          {{ none }}
        {% endif %}

      vt_last_seen_age_min: >-
        {% if vt_last_seen_dt %}
          {{ ((now() - vt_last_seen_dt).total_seconds() / 60) | round(0) }}
        {% else %}
          {{ none }}
        {% endif %}

      mode_last_changed: "{{ trigger.event.data.new_state.last_changed }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ to_state in ['internal', 'external_2'] }}"
        sequence:
          - service: repairs.create
            data:
              issue_id: "{{ issue_id }}"
              title: "{{ friendly_name }} External Temperature Missing"
              severity: error
              domain: climate
              persistent: true
              description: >
                **ERROR:** {{ friendly_name }} is in **{{ to_state }}** and is using its
                **internal temperature sensor** because external temperature is not being applied.

                {% if to_state == 'external_2' %}
                **external_2** indicates fallback after missing external temperature updates.
                {% else %}
                **internal** indicates it is configured to use its internal sensor.
                {% endif %}

                **Versatile Thermostat status ({{ room_key }}):**
                - VT last temperature date sensor: `{{ vt_last_seen_sensor }}`
                - Value: {{ vt_last_seen_raw }}
                {% if vt_last_seen_age_min is not none %}
                - Age: {{ vt_last_seen_age_min }} minute(s)
                {% endif %}

                **TRV mode transition:**
                - From: `{{ from_state }}` → To: `{{ to_state }}`
                - Mode last changed: {{ mode_last_changed }}

                **Reset workflow:**
                Dismiss this repair when you’ve investigated.
                Dismissal will set `{{ entity_id }}` back to **external**.

      - conditions:
          - condition: template
            value_template: "{{ to_state == 'external_3' }}"
        sequence:
          - service: repairs.create
            data:
              issue_id: "{{ issue_id }}"
              title: "{{ friendly_name }} External Temperature Intermittent"
              severity: warning
              domain: climate
              persistent: true
              description: >
                **WARNING:** {{ friendly_name }} entered **external_3**.
                External temperature input resumed after fallback, but reliability is intermittent.

                **Versatile Thermostat status ({{ room_key }}):**
                - VT last temperature date sensor: `{{ vt_last_seen_sensor }}`
                - Value: {{ vt_last_seen_raw }}
                {% if vt_last_seen_age_min is not none %}
                - Age: {{ vt_last_seen_age_min }} minute(s)
                {% endif %}

                **TRV mode transition:**
                - From: `{{ from_state }}` → To: `{{ to_state }}`
                - Mode last changed: {{ mode_last_changed }}

                **Reset workflow:**
                Dismiss this repair after investigating.
                Dismissal will set `{{ entity_id }}` back to **external**.
