apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-whisper-config
spec:
  storageClassName: ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.voice.whisper.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-whisper
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: wyoming-whisper
      app.kubernetes.io/name: wyoming-whisper
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: wyoming-whisper
        app.kubernetes.io/name: wyoming-whisper
    spec:
      containers:
      - name: wyoming-whisper
        image: '{{ .Values.voice.whisper.image.repository }}:{{ .Values.voice.whisper.image.tag }}'
        ports:
        - name: wyoming
          containerPort: 10300
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PUID
          value: '1000'
        - name: PGID
          value: '5000'
        - name: WHISPER_MODEL
          value: '{{ .Values.voice.whisper.model }}'
        - name: WHISPER_LANG
          value: '{{ .Values.voice.whisper.language }}'
        - name: WHISPER_BEAM
          value: '{{ .Values.voice.whisper.beamSize }}'
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            memory: 4Gi
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: wyoming-whisper-config
---
apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper
spec:
  type: ClusterIP
  ports:
  - name: wyoming
    port: 10300
    targetPort: 10300
    protocol: TCP
  selector:
    app.kubernetes.io/instance: wyoming-whisper
    app.kubernetes.io/name: wyoming-whisper
