argo-cd:
  global:
    revisionHistoryLimit: 0
    domain: argocd.mobrockers.com

  dex:
    enabled: false
  applicationSet:
    replicas: 0
    serviceAccount:
      create: false
      allowAnyNamespace: false
  notifications:
    enabled: false

  configs:
    secret:
      createSecret: true
    cm:
      create: false
      exec.enabled: true
    rbac:
      create: false
    params:
      server.insecure: 'true'
      # controller.diff.server.side: 'true'

  controller:
    replicas: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  redis:
    enabled: true

  server:
    replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    ingress:
      enabled: true
      tls: false
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hostname: argocd.mobrockers.com
      extraTls:
      - hosts:
        - argocd.mobrockers.com

  repoServer:
    replicas: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
