apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    secretKey: AgBaCvK1y+kfLJH8sQU9wuTIJd5eobL+jiMD4j0blr0J5bEATvn3BGkqVLQWa+7pvUL0B91TKGvnDCeC/qAJCwDrv73VLKGZuHZPxoVDUHa3z1/uVImTX4EH5ZT63sftcS8fLFK6sZeoH3jw2ApX4x/72TWpXdE1s2X9SbkHJrH+IwoysAENO01JAbyXmc1PxtLucPd0iIz67Pw1KO1QamMsHy41nbgS+7tZxhbCMozJ+xIPSlxiJJ5RvMCEuER1FOIz070C07VH01aprBCPDD0PYDqQCG15qSf02KONvvF0bflTFIxyhTdjWnbkRepBBsOKLkJrrLEE7y4NbOevdd0fLcltgjDpTpziBanpVI/rHp0e6eTqtzNO+J1UVP51IkeUTphXhRxEQM03qU4v+z1aEBgQVk+E47BHHM0Shkh85F1FB/WSAKK5jbL8Ogrj3TDfQLTdXHvsSrnmqYUsl7Dlrk2rD+Pa6jrvpkyETXhCUKAH8okzZvCObl5fJzia773140PbYfugpE5cG/NunSMJrbpdZxxZMkLb8iYCajATF7iJd/7r+jLf9mtVNq9IO/SpFFn0PXS3b46BSwmOUs17nMyW4ajPshE1V/R6svtGkCWVuuqJSWlPj0ktUcx5KlAjKlyk0KI2PazORi/9rFnEG4INJSS2zg9luRpMHnNWwqhCjYGLUwp1lR0/UFsXxVVXF1RzA0hpV8l+namuhjEbcatiY5r1+WsXwd/VGlIW9I8KpbIOS/tdOae3IXnzslM=
