ollama:

  nodeSelector:
    node-role.kubernetes.io/gpu: ""
  tolerations:
    - key: node-role.kubernetes.io/gpu
      operator: Exists

  ollama:
    # -- List of models to pull at container startup
    models:
      clean: true
      pull:
      - bge-m3
      run:
      - bge-m3

  persistentVolume:
    enabled: true
    storageClass: local-nvme
    size: 10Gi

  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      memory: 16Gi

  extraEnv:
  - name: OLLAMA_CONTEXT_LENGTH
    value: "8192"
