apiVersion: v2
name: rook-ceph-cluster
version: 0.0.0

dependencies:
  - name: rook-ceph-cluster
    version: v1.20.7
    repository: https://charts.rook.io/release
  - name: extended-ceph-exporter
    version: 1.0.1
    repository: oci://ghcr.io/florisfeddema/charts
