rook-ceph-cluster:

  cephBlockPools:
  - name: builtin-mgr
    spec:
      name: .mgr
      enableCrushUpdates: true
      enableRBDStats: true
      failureDomain: zone
      replicated:
        size: 2
    storageClass:
      enabled: false
  - name: ceph-blockpool
    spec:
      enableCrushUpdates: true
      enableRBDStats: true
      failureDomain: zone
      replicated:
        size: 2
        hybridStorage:
          primaryDeviceClass: nvme
          secondaryDeviceClass: hdd
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: WaitForFirstConsumer
      mountOptions:
      - discard
      parameters:
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"

  cephBlockPoolsVolumeSnapshotClass:
    enabled: true
    name: ceph-block
    isDefault: true
    deletionPolicy: Delete
