rook-ceph-cluster:
  cephFileSystems:
  - name: ceph-filesystem
    spec:
      metadataPool:
        enableCrushUpdates: true
        failureDomain: zone
        replicated:
          size: 2
          hybridStorage:
            primaryDeviceClass: nvme
            secondaryDeviceClass: hdd
      dataPools:
      - name: data0
        enableCrushUpdates: true
        failureDomain: zone
        replicated:
          size: 2
          hybridStorage:
            primaryDeviceClass: nvme
            secondaryDeviceClass: hdd
      metadataServer:
        activeCount: 1
        activeStandby: true
        resources:
          requests:
            cpu: 10m
            memory: 1Gi
          limits:
            memory: 3Gi
        priorityClassName: system-cluster-critical
    storageClass:
      enabled: true
      isDefault: false
      name: ceph-filesystem
      pool: data0
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
      parameters:
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"

  cephFileSystemVolumeSnapshotClass:
    enabled: true
    name: ceph-filesystem
    isDefault: false
    deletionPolicy: Delete
