apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: qwen3-0.6b
spec:
  prefetch: {{ .Values.models.prefetch }}
  refreshPolicy: OnChange
  format: gguf
  source: hf://Qwen/Qwen3-0.6B-GGUF
  files:
    - Qwen3-0.6B-Q8_0.gguf
  quantization: Q8_0
  hardware:
    accelerator: intel
    gpu:
      enabled: true
      vendor: intel
      resourceClaims:
        - name: i915
          resourceClaimTemplateName: uhd-730
