gateway-helm:
  deployment:
    envoyGateway:
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
    replicas: 2

  config:
    envoyGateway:
      provider:
        type: Kubernetes
        kubernetes:
          deploy:
            type: GatewayNamespace
      logging:
        level:
          default: info # debug/info/error/warn

gateway-addons-helm:
  alloy:
    enabled: false
  loki:
    enabled: false
  tempo:
    enabled: false
  fluent-bit:
    enabled: false
  opentelemetry-collector:
    enabled: false
  grafana:
    enabled: false
  prometheus:
    enabled: false
  dashboard:
    labels:
      grafana_dashboard: '1'