apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rook-ceph-objectstore-s3-route
spec:
  hostnames: ['s3.mobrockers.com', '*.s3.mobrockers.com']
  parentRefs:
  - name: private
    namespace: envoy-gateway
    sectionName: apex-s3-mobrockers-com
  - name: private
    namespace: envoy-gateway
    sectionName: s3-mobrockers-com
  rules:
  - backendRefs:
    - name: rook-ceph-rgw-ceph-objectstore
      port: 80
    # matches:
    # - path:
    #     type: PathPrefix
    #     value: /
    timeouts:
      request: 0s
      backendRequest: 0s
