apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rook-ceph-objectstore-s3-route
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway
    sectionName: s3-https
  hostnames: ["*.s3.mobrockers.com"]
  rules:
  - backendRefs:
    - name: rook-ceph-rgw-ceph-objectstore
      port: 80
    timeouts:
      request: 0s
      backendRequest: 0s
