kyverno-policies:
  podSecurityStandard: restricted
  podSecuritySeverity: low

route:
  enabled: true
  hostnames:
  - kyverno.mobrockers.com
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway
    sectionName: web-https

kyverno:
  crds:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true

  openreports:
    enabled: true
    installCrds: true

  grafana:
    enabled: true

  features:
    mutatingAdmissionPolicyReports: 
      enabled: true
    generateMutatingAdmissionPolicy:
      enabled: false # Can enable from 1.34?
    policyExceptions:
      enabled: true

  admissionController:
    replicas: 3
    revisionHistoryLimit: 0
    serviceMonitor:
      enabled: true

  backgroundController:
    revisionHistoryLimit: 0
    serviceMonitor:
      enabled: true

  cleanupController:
    revisionHistoryLimit: 0
    serviceMonitor:
      enabled: true

  reportsController:
    revisionHistoryLimit: 0
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 500m
        memory: 129Mi
    serviceMonitor:
      enabled: true

policy-reporter:
  revisionHistoryLimit: 0
  periodicSync:
    enabled: true

  metrics:
    enabled: true

  ui:
    enabled: true
    revisionHistoryLimit: 0

    openIDConnect:
      enabled: true
      callbackUrl: https://kyverno.mobrockers.com/callback
      secretRef: authentik-credentials

  plugin:
    kyverno:
      enabled: true
      revisionHistoryLimit: 0
      blockReports:
        enabled: true
        results:
          keepOnlyLatest: true
          source: 'Kyverno Event'
    trivy:
      enabled: true
      revisionHistoryLimit: 0

  monitoring:
    enabled: true
    grafana:
      namespace: ~
