{{- range $certificate := .Values.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certificate.name }}
spec:
  dnsNames: {{ $certificate.dnsNames | toYaml | nindent 4 }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-letsencrypt-dns
  revisionHistoryLimit: 1
  secretName: {{ $certificate.name }}
---
{{- end }}
