apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: default-public-client-traffic-policy
spec:
  headers:
    lateResponseHeaders:
      set:
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains
        - name: "x-content-type-options"
          value: "nosniff"
  path:
    escapedSlashesAction: KeepUnchanged
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public
  tls:
    minVersion: '1.3'
