apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy
spec:
  provider:
    type: Kubernetes
    kubernetes:
        replicas: 3
        container:
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              memory: 1Gi
      envoyService:
        annotations:
          'io.cilium/lb-ipam-ips': {{ .Values.privateIp }}
        externalTrafficPolicy: Local
