image:
  repository: ghcr.io/linuxserver/prowlarr
  tag: 2.0.5

metrics:
  image:
    repository: ghcr.io/onedr0p/exportarr
    tag: v2.3.0

route:
  enabled: true
  hostnames:
    - prowlarr.mobrockers.com
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
      sectionName: web-https
