apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-certificate-bootstrap
  namespace: prometheus-etcd-exporter
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"