apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: etcd-certificate-bootstrap-talos-secrets
  namespace: prometheus-etcd-exporter
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  roles:
    - os:admin