rook-ceph-cluster:

  monitoring:
    enabled: true
    createPrometheusRules: true

  ingress:
    dashboard:
      host:
        name: ceph.mobrockers.com
      tls:
      - hosts:
        - ceph.mobrockers.com

  cephClusterSpec:
    cephVersion:
      image: quay.io/ceph/ceph:v19.2.2

    csi:
      readAffinity:
        enabled: true

    mon:
      count: 3
      # failureDomainLabel: topology.kubernetes.io/zone
      # zones:
      # - name: '1'
      # - name: '2'
      # - name: '3'

    mgr:
      count: 2
      modules:
      - name: pg_autoscaler
        enabled: true
    dashboard:
      ssl: false

    network:
      provider: host
      encryption:
        enabled: false
      compression:
        enabled: false
      addressRanges:
        public: ['10.0.102.0/24']
        cluster: ['10.0.104.0/24']

    storage:
      useAllNodes: false
      useAllDevices: false
      nodes:
      # - name: talos-worker-1
      #   devices:
      #   - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
      #   config:
      #     deviceClass: nvme
      - name: talos-worker-2
        devices:
        - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
        config:
          deviceClass: nvme
      - name: talos-worker-3
        devices:
        - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
        config:
          deviceClass: nvme
      - name: talos-worker-4
        devices:
        - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
        config:
          deviceClass: nvme
      - name: talos-worker-5
        devices:
        - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
        config:
          deviceClass: nvme
