rook-ceph-cluster:

  # -- A list of CephObjectStore configurations to deploy
  # @default -- See [below](#ceph-object-stores)
  cephObjectStores:
    # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Object-Storage/ceph-object-store-crd.md#object-store-settings for available configuration
  - name: ceph-objectstore
    spec:
      metadataPool:
        failureDomain: zone
        replicated:
          size: 2
      dataPool:
        failureDomain: zone
        replicated:
          size: 2
      allowUsersInNamespaces: ['*']
      gateway:
        port: 80
        resources:
          requests:
            cpu: 10m
            memory: 200Mi
          limits:
            memory: 500Mi
        # securePort: 443
        # sslCertificateRef:
        instances: 1
        priorityClassName: system-cluster-critical
        opsLogSidecar:
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 100Mi
    storageClass:
      enabled: true
      name: ceph-bucket
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      annotations: {}
      labels: {}
      # see https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md#storageclass for available configuration
      parameters: {}
        # note: objectStoreNamespace and objectStoreName are configured by the chart
    ingress:
      # Enable an ingress for the ceph-objectstore
      enabled: false
      # annotations: {}
      host:
        name: s3.mobrockers.com
      #   path: /
      #   pathType: Prefix
      tls:
      - hosts:
        - s3.mobrockers.com
      #   secretName: ceph-objectstore-tls
      # ingressClassName: nginx
