rook-ceph:

  revisionHistoryLimit: 0
  resources:
    requests:
      cpu: 2
      memory: 128Mi
    limits:
      memory: 1Gi
  csi:
    enableMetadata: true
    topology:
      enabled: true
      domainLabels: kubernetes.io/hostname,topology.kubernetes.io/zone
    enableLiveness: true
    serviceMonitor:
      enabled: true
  monitoring:
    enabled: true
