rook-ceph:
  revisionHistoryLimit: 0
  csi:
    enableMetadata: true
    topology:
      enabled: true
      domainLabels: kubernetes.io/hostname,topology.kubernetes.io/zone
    serviceMonitor:
      enabled: true
    enableLiveness: true
  monitoring:
    enabled: true

rook-ceph-cluster:
  dataDirHostPath: /var/lib/rook

  # ingress:
  #   dashboard:
  #     annotations:
  #       nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  #     host:
  #       name: ceph.mobrockers.com
  #     tls:
  #     - hosts:
  #       - ceph.mobrockers.com

  cephClusterSpec:
    cephVersion:
      image: quay.io/ceph/ceph:v19.2.1

    mon:
      count: 3
      failureDomainLabel: topology.kubernetes.io/zone
      zones:
      - name: '1'
      - name: '2'
      - name: '3'

    mgr:
      count: 2
      modules:
      - name: pg_autoscaler
        enabled: true

    network:
      provider: host
      encryption:
        enabled: false
      compression:
        enabled: false
      addressRanges:
        public: ['']
        cluster: ['']

    storage:
      useAllNodes: false
      useAllDevices: false
      nodes:
      - name: talos-worker-1
        devices:
        - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
        config:
          deviceClass: nvme
      - name: talos-worker-2
        devices:
        - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
        config:
          deviceClass: nvme
      - name: talos-worker-3
        devices:
        - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
        config:
          deviceClass: nvme
      - name: talos-worker-4
        devices:
        - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
        config:
          deviceClass: nvme
      - name: talos-worker-5
        devices:
        - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
        config:
          deviceClass: nvme

  cephBlockPools:
  - name: ceph-blockpool
    spec:
      failureDomain: zone
      replicated:
        size: 3
    storageClass:
      enabled: true
      isDefault: false

  cephFileSystems:
  - name: ceph-filesystem
    spec:
      dataPools:
      - name: data0
        failureDomain: zone
        replicated:
          size: 3

  cephObjectStores:
  - name: ceph-objectstore
    spec:
      metadataPool:
        failureDomain: zone
        replicated:
          size: 3
      dataPool:
        failureDomain: zone
        erasureCoded:
          dataChunks: 2
          codingChunks: 1
        parameters:
          bulk: "true"
      ingress:
        enabled: false
        host:
          name: s3.mobrockers.com
        tls:
        - hosts:
          - s3.mobrockers.com
  monitoring:
    enabled: true
    createPrometheusRules: true