apiVersion: v2
name: kyverno
version: 0.0.0

dependencies:
  - name: kyverno
    version: 3.4.1
    repository: oci://ghcr.io/kyverno/charts/kyverno
  - name: policy-reporter
    version: 3.1.4
    repository: oci://ghcr.io/kyverno/charts/policy-reporter
  # - name: kyverno-policies
  #   version: 1.13.0
  #   repository: oci://ghcr.io/kyverno/charts/kyverno-policies
