kyverno:

  crds:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
    migration:
      enabled: false

  admissionController:
    replicas: 3

  backgroundController:
    replicas: 2
  cleanupController:
    replicas: 2
  reportsController:
    replicas: 2