searxng:
  revisionHistoryLimit: 0
  config:
    useDefaultSettings: false
    settings:
      use_default_settings:
        engines:
          remove:
            - brave
            - brave images
            - brave videos
            - brave news
            - google
            - torch
            - ahmia
            - wikidata
            - bing
      general:
        enable_metrics: false
      server:
        base_url: http://searxng.searxng.svc.cluster.local:8080
        limiter: false
      search:
        safe_search: 0
        autocomplete: ""
        formats:
          - html
          - json  # Critical for Open WebUI integration
      engines: []
  persistence:
    cache:
      storageClass: ceph-filesystem
      accessMode: ReadWriteMany
