---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-credentials
  namespace: argocd
spec:
  encryptedData:
    client_id: {{ .Values.authentication.clientIdSealed }}
    client_secret: {{ .Values.authentication.clientSecretSealed }}
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
