apiVersion: v1
kind: Pod
metadata:
  name: cephfs-xattr-fix
  namespace: rook-ceph
spec:
  restartPolicy: Never
  containers:
  - name: deb
    image: debian:bookworm-slim
    securityContext: { privileged: true, capabilities: { add: ["SYS_ADMIN"] } }
    command: ["bash","-lc","sleep infinity"]
    volumeMounts:
    - name: rook-mon   # mount secret here, NOT /etc/ceph
      mountPath: /rook/mon
    - name: fuse
      mountPath: /dev/fuse
  volumes:
  - name: rook-mon
    secret: { secretName: rook-ceph-mon }
  - name: fuse
    hostPath: { path: /dev/fuse, type: CharDevice }