apiVersion: v1
kind: Pod
metadata:
  name: cephfs-xattr-fix
  namespace: rook-ceph
spec:
  restartPolicy: Never
  containers:
  - name: ceph
    image: quay.io/ceph/ceph:v19
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      capabilities:
        add: ["SYS_ADMIN"]
    command: ["bash","-lc","sleep infinity"]
    volumeMounts:
    - name: ceph-conf
      mountPath: /etc/ceph
    - name: fuse
      mountPath: /dev/fuse
  volumes:
  - name: ceph-conf
    secret:
      secretName: rook-ceph-mon       # contains ceph.conf and admin keyring
  - name: fuse
    hostPath:
      path: /dev/fuse
      type: CharDevice
